# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4aa04e6a085072a4cc6568e4a207bb487c80c6ef5068621924ce696e2212e3d536e49a507645346870438be4d474cb1aa3d8664a12ed786b5a832afaec7e96c4

test:
  secret_key_base: 5d78831cd78cb986e3c809b6b4139b62ae5f2358e46d2fa4c31939db7b71c7ac19c4f843831ee2d76afcde1087a233a998653184103e6b563fec6838a5f5ff6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
